"""Add network hosts and menu permissions

Revision ID: 041dfd35b1de
Revises: a7ab140dda1d
Create Date: 2025-10-24 11:22:09.295504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041dfd35b1de'
down_revision = 'a7ab140dda1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_key', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_key', 'role', 'user_id', name='uq_menu_permission')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_permission')
    # ### end Alembic commands ###
