"""Add network table

Revision ID: 18309837215b
Revises: 2f5dc629f8bd
Create Date: 2025-10-24 10:34:06.291534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18309837215b'
down_revision = '2f5dc629f8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('site', sa.String(length=120), nullable=True),
    sa.Column('vlan', sa.String(length=60), nullable=True),
    sa.Column('gateway', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cidr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network')
    # ### end Alembic commands ###
