"""empty message

Revision ID: 2f5dc629f8bd
Revises: ab523ef0fd16
Create Date: 2025-10-23 14:21:45.278568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5dc629f8bd'
down_revision = 'ab523ef0fd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('custom_tag', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('cpu', sa.String(length=150), nullable=True),
    sa.Column('ram_gb', sa.String(length=50), nullable=True),
    sa.Column('storage', sa.String(length=120), nullable=True),
    sa.Column('gpu', sa.String(length=150), nullable=True),
    sa.Column('operating_system', sa.String(length=150), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('hostname', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('rack', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('condition', sa.String(length=120), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_end', sa.Date(), nullable=True),
    sa.Column('support_vendor', sa.String(length=150), nullable=True),
    sa.Column('support_contract', sa.String(length=150), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_on', sa.Date(), nullable=True),
    sa.Column('accessories', sa.String(length=255), nullable=True),
    sa.Column('power_supply', sa.String(length=120), nullable=True),
    sa.Column('bios_version', sa.String(length=120), nullable=True),
    sa.Column('firmware_version', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag'),
    sa.UniqueConstraint('custom_tag')
    )
    op.create_table('software_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('vendor', sa.String(length=150), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('license_type', sa.String(length=120), nullable=True),
    sa.Column('license_key', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('custom_tag', sa.String(length=120), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=120), nullable=True),
    sa.Column('environment', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('cost_center', sa.String(length=120), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('support_vendor', sa.String(length=150), nullable=True),
    sa.Column('support_email', sa.String(length=150), nullable=True),
    sa.Column('support_phone', sa.String(length=80), nullable=True),
    sa.Column('contract_url', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_on', sa.Date(), nullable=True),
    sa.Column('usage_scope', sa.String(length=150), nullable=True),
    sa.Column('deployment_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software_asset')
    op.drop_table('hardware_asset')
    # ### end Alembic commands ###
