"""add checksum and job id to transfers

Revision ID: 9e48e1cd10c0
Revises: c6c2fd9c7db1
Create Date: 2025-11-17 14:35:52.271334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e48e1cd10c0'
down_revision = 'c6c2fd9c7db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_agent_download_link', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fleet_agent_download_link_token_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_fleet_agent_link_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('fleet_file_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checksum', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('source_job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fleet_scheduled_job', ['source_job_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fleet_message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_fleet_message_doc_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_fleet_message_doc_key'))
        batch_op.create_index(batch_op.f('ix_fleet_message_doc_key'), ['doc_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_message_doc_key'))
        batch_op.create_index(batch_op.f('ix_fleet_message_doc_key'), ['doc_key'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_fleet_message_doc_key'), ['doc_key'])

    with op.batch_alter_table('fleet_file_transfer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_job_id')
        batch_op.drop_column('checksum')

    with op.batch_alter_table('fleet_agent_download_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_fleet_agent_link_user'), 'user', ['created_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_unique_constraint(batch_op.f('fleet_agent_download_link_token_key'), ['token'])

    # ### end Alembic commands ###
