"""Add fleet remote command / file transfer columns

Revision ID: bacba217dc0f
Revises: 11074d820bc0
Create Date: 2025-11-13 16:15:16.301089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacba217dc0f'
down_revision = '11074d820bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address_book_entry', schema=None) as batch_op:
        batch_op.drop_column('Name;Company;Job Title;Department;Email;Phone;Mobile;Website;Ad')
        batch_op.drop_column('Job Title')
        batch_op.drop_column('From Email')
        batch_op.drop_column('Postal Code')
        batch_op.drop_column('address')
        batch_op.drop_column('actions')

    with op.batch_alter_table('fleet_file_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('fleet_remote_command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_remote_command', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')

    with op.batch_alter_table('fleet_file_transfer', schema=None) as batch_op:
        batch_op.drop_column('consumed_at')

    with op.batch_alter_table('address_book_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actions', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Postal Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('From Email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Job Title', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Name;Company;Job Title;Department;Email;Phone;Mobile;Website;Ad', sa.VARCHAR(length=256), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
